### PR TITLE
test: cover quality markdown newline escaping

### LINKED ISSUE #619: Tests: cover DataQualityReport markdown escaping
## Problem
Coverage is missing for this audit area: quality report markdown needs tests for pipes and newlines.

## Evidence / audit context
- Issue title: Tests: cover DataQualityReport markdown escaping
- Audit focus: quality report markdown needs tests for pipes and newlines.
- Labels selected: type: tests, area: quality, priority: medium, difficulty: beginner, status: ready, size: s, gssoc, gssoc: good first issue, gssoc: level 1
- Existing open issues were checked before this candidate was selected.

## Reproduction or impacted flow
Exercise the API, module, or workflow named in the title with a minimal fixture. For non-bug tasks, use this as the impacted user/contributor flow.

## Suggested fix
Add focused pytest, notebook, or CI smoke coverage that fails before the fix and passes after.

## Acceptance criteria
- A focused regression test, smoke test, benchmark, or docs check is added where applicable.
- The behavior is deterministic and has a clear user-facing error or documented contract.
- Existing CSV, pandas interop, pipeline, schema, quality, and packaging tests continue to pass.

_Created from the deep Arnio audit backlog._

### PR DESCRIPTION
**Pull request by saurabhhhcodes**
## Summary
- add focused regression coverage for `DataQualityReport.to_markdown()` newline escaping in column table cells
- verify newlines in column names, semantic types, and warnings render as `<br>` instead of splitting Markdown rows

Fixes #619

## Validation
- `git diff --check`
- `python3 -m py_compile tests/test_quality.py arnio/quality.py`
- `python3 -m pytest tests/test_quality.py::test_report_to_markdown_escapes_newlines_in_column_cells -q`

## Note
`python3 -m pytest tests/test_quality.py -q` currently has unrelated local failures before/around CSV profiling because the installed native extension reports `AttributeError: 'arnio._arnio_cpp.CsvConfig' object has no attribute 'mode'`. The new markdown-only regression test passes in isolation.

## GSSoC labels requested
This issue is marked `gssoc`, `gssoc: good first issue`, `gssoc: level 1`, and `type: tests`; please add/keep the tracker-required scoring labels if this is accepted.

### CODE REVIEW

**Review by im-anishraj — CHANGES_REQUESTED** [review]
Thanks @saurabhhhcodes for the focused test coverage. The diff is small and CI is green.

I’m not merging this PR right now because #619 is already assigned to @arshey63, and we need to keep GSSoC assignments fair and predictable. Please avoid opening PRs for issues that are already claimed by another contributor unless the assignee has handed it off or a maintainer has reassigned the issue.

If #619 becomes available later, I can reconsider this work. For now, I’m leaving the PR open but not approving/merging it.

**Comment by saurabhhhcodes** [comment]
Closing this to respect the current GSSoC assignment on #619. Thanks for the clear note; I will avoid picking up already-assigned issues unless a maintainer reassigns or explicitly asks for another implementation.
